version: 1

jobs:
  format:
    steps:
      - run: test -z "$(gofmt -l .)"

  vet:
    steps:
      - run: go vet ./...

  test:
    needs:
      - format
      - vet
    steps:
      - run: go test ./...

  build:
    needs:
      - test
    steps:
      - run: go build -o build/forge ./cmd/forge
